version: '3'
services:
  redis:
    container_name: redis
    image: redis:6-alpine
    restart: unless-stopped
    ports:
    - 6379:6379
    volumes:
    - redis:/data
  postgres:
    container_name: postgres
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgress
    - POSTGRES_DB=postgres
    ports:
    - 5432:5432
    volumes:
    - pgdata:/var/lib/postgresql/data
    networks:
    - sonarnet
  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    environment:
    - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
    - SONAR_JDBC_PASSWORD=postgress
    - SONAR_JDBC_USERNAME=postgres
    ports:
    - 9000:9000
    - 9092:9092
    links:
    - postgres
    volumes:
    - sonarqube_extensions:/opt/sonarqube/extensions
    - sonarqube_logs:/opt/sonarqube/logs
    - sonarqube_data:/opt/sonarqube/data
    networks:
    - sonarnet
  swaggerui:
    container_name: swaggerui
    image: swaggerapi/swagger-editor
    ports:
    - 8030:8080
  mongo:
    image: mongo
    networks:
    - backend
    restart: on-failure
    ports:
    - 27017:27017
  mongo-express:
    image: mongo-express
    networks:
    - backend
    restart: always
    ports:
    - 8020:8081
  mongoclient:
    image: mongoclient/mongoclient
    networks:
    - backend
    restart: 'no'
    ports:
    - 8040:3000
    environment:
      MONGO_URL: mongodb://mongo:27017/mydb
      MONGOCLIENT_DEFAULT_CONNECTION_URL: mongodb://mongo:27017/mydb
networks:
  backend: null
  sonarnet: null
volumes:
  redis: null
  pgdata: null
  sonarqube_extensions: null
  sonarqube_logs: null
  sonarqube_data: null
  jenkins: null