version: '3'
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    ports:
      - 8040:9000
      - 9092:9092
    networks:
      - sonarnet
  jenkins:
    container_name: jenkins
    image: jenkinsci/blueocean
    restart: unless-stopped
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    ports:
      - 8030:8080
    links:
      - sonarqube
    networks:
      - sonarnet
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
  swaggerui:
    container_name: swaggerui
    image: swaggerapi/swagger-editor
    ports:
      - 8020:8080
  redis:
    container_name: redis
    image: redis:6-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - backend
  mongo:
    container_name: mongo
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017
    networks:
      - backend
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - 8010:8081
    links:
      - mongo
    networks:
      - backend
networks:
  sonarnet: null
  backend: null
volumes:
  redis: null
  jenkins-docker-certs: null
  jenkins-data: null
