openapi: 3.0.3
info:
  title: fcBackend-API
  description: This is a description of the fcBackend API
  version: 1.0.0
  license:
    name: GNU 3.0
    url: https://www.gnu.org/licenses/gpl-3.0.en.html

paths:
  /quizz:
    get:
      summary: Returns a new Quizz Session
      description: each Quizz Session has a beginning and an end
      operationId: getSession
      responses:
        '200':
          description: A JSON Array of a session object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IQuizzSession'
  /quizz/{sessionId}:
    get:
      summary: requests a new questions
      operationId: getNextQuestion
      parameters:
        - name: sessionId
          in: path
          required: true
          description: session String as created by get
          schema:
            $ref: '#/components/schemas/ISessionId'
      responses:
        '200':
          description: deletes the session. The quizz has been finished afterwards
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IQuestion'
        '410':
          description: session id not found
    delete:
      summary: finishs a QuizzSession and deletes all related data
      operationId: deleteSession
      parameters:
        - name: sessionId
          in: path
          required: true
          description: session String as created by get
          schema:
            $ref: '#/components/schemas/ISessionId'
      responses:
        '200':
          description: deletes the session. The quizz has been finished afterwards
        '410':
          description: session id not found
components:
  schemas:
    ISessionId:
      type: string
      description: an unique string which identifies a session
      example: 1f9d14f1-6179-4dbd-9c53-915412622640
    IQuestion:
      type: object
      properties:
        id: 
          type: string
        answers:
          type: array
          items: 
            type: string
    IQuizzSession:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/ISessionId'
        creationTime:
          type: string
          format: date-time
          example: '2020-05-19T12:45:32.538Z'
servers:
  - url: 'http://localhost:8000/'
    variables: {}
    description: dev-Server
